spring:
  application:
    name: 02-back
  data:
    mongodb:
      uri: mongodb+srv://leolandin:leo02842010@02-mongo-ufnvy.gcp.mongodb.net/02-db?retryWrites=true&w=majority
      database: 02-db

zerotwo:
  jwt:
    secret: BDF9ECE42A6CCC084CA2AC71D83F571EA02AFF8CB7F6F7EEE10658EB09F2D289
    expires: 21600000
  recaptcha:
    secret: 6LcXn9cUAAAAAN4cL08s82_dJpdPGwPlZg-_ixin
  mail:
    user: automatico.project.02@gmail.com
    pass: nmCKp5A6pi